// Generated by CoffeeScript 1.6.3
(function() {
  var tests;

  require.config({
    baseUrl: 'js/',
    paths: {
      jquery: 'lib/jquery/jquery.min',
      mocha: 'lib/mocha/mocha',
      chai: 'lib/chai/chai',
      sinon: 'lib/sinonjs/sinon'
    },
    shim: {
      jquery: {
        exports: 'jQuery'
      },
      mocha: {
        exports: 'mocha'
      },
      sinon: {
        exports: 'sinon'
      }
    }
  });

  tests = ['ajax'];

  tests = tests.map(function(test) {
    return 'test/' + test;
  });

  require(['mocha'], function(mocha) {
    mocha.setup('bdd');
    return require(tests, function() {
      return mocha.run();
    });
  });

}).call(this);
